version: "3.5"


services:
  #================================
  #      POSTGRESQL DATABASE
  #================================
  home-bar-postgresql:
    container_name: home-bar-postgresql
    image: postgres:12-alpine
    hostname: home-bar-postgresql
    volumes:
      - .data/home-bar-postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=phoenix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=homebar
    networks:
      - home-bar-network
    restart: always  

  #================================
  #    POSTGRESQL DATABASE GUI
  #================================
  home-bar-postgresql-gui:
    container_name: home-bar-postgresql-gui
    image: dpage/pgadmin4
    hostname: home-bar-postgresql-gui
    ports:
      - 5050:80
    volumes:
       - .data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - home-bar-postgresql
    networks:
      - home-bar-network
    restart: always


#================================
#         NETWORK
#================================
networks:
  home-bar-network:
    external:
      name: home-bar-network